create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null,
  sort_order integer not null default 0
);

create table if not exists labels (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  color text not null
);

create table if not exists listings (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('skill', 'plugin', 'model')),
  title text not null,
  slug text not null unique,
  icon text not null,
  description text not null,
  category_id bigint not null references categories(id),
  compatibility text not null check (compatibility in ('claude_code', 'codex', 'both', 'local_lm')),
  install_url text not null,
  github_url text not null,
  status text not null check (status in ('draft', 'published', 'archived')),
  featured boolean not null default false,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists listing_labels (
  listing_id bigint not null references listings(id) on delete cascade,
  label_id bigint not null references labels(id) on delete cascade,
  primary key (listing_id, label_id)
);

create table if not exists commands (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references listings(id) on delete cascade,
  label text not null,
  command text not null,
  sort_order integer not null default 0
);

create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  listing_id bigint references listings(id) on delete set null,
  category_slug text,
  label_slug text,
  search_query text,
  result_count integer,
  target_url text,
  path text,
  created_at timestamptz not null
);

alter table categories enable row level security;
alter table labels enable row level security;
alter table listings enable row level security;
alter table listing_labels enable row level security;
alter table commands enable row level security;
alter table analytics_events enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'categories' and policyname = 'Public read categories'
  ) then
    create policy "Public read categories" on categories for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'labels' and policyname = 'Public read labels'
  ) then
    create policy "Public read labels" on labels for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'listings' and policyname = 'Public read published listings'
  ) then
    create policy "Public read published listings" on listings for select using (status = 'published');
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'listing_labels' and policyname = 'Public read listing labels'
  ) then
    create policy "Public read listing labels" on listing_labels for select using (
      exists (
        select 1
        from listings
        where listings.id = listing_labels.listing_id
          and listings.status = 'published'
      )
    );
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'commands' and policyname = 'Public read listing commands'
  ) then
    create policy "Public read listing commands" on commands for select using (
      exists (
        select 1
        from listings
        where listings.id = commands.listing_id
          and listings.status = 'published'
      )
    );
  end if;
end $$;

create index if not exists listings_status_idx on listings(status);
create index if not exists listings_category_id_idx on listings(category_id);
create index if not exists listings_slug_idx on listings(slug);
create index if not exists listing_labels_listing_id_idx on listing_labels(listing_id);
create index if not exists listing_labels_label_id_idx on listing_labels(label_id);
create index if not exists commands_listing_id_idx on commands(listing_id);
create index if not exists analytics_events_event_type_idx on analytics_events(event_type);
create index if not exists analytics_events_listing_id_idx on analytics_events(listing_id);
create index if not exists analytics_events_search_query_idx on analytics_events(search_query);
